# MAC Comprehensive Experiments Configuration
experiment_settings:
  name: "MAC_Comprehensive_Analysis"
  description: "Complete MAC training across all datasets and SNR levels"
  output_dir: "comprehensive_mac_experiments"
  log_level: "INFO"

# Dataset configurations
datasets:
  RML201610A:
    enabled: true
    epochs: 240
    batch_size: 128
    snr_levels: [-20, -18, -16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
    num_classes: 11
    class_names: ['8PSK', 'AM-DSB', 'AM-SSB', 'BPSK', 'CPFSK', 'GFSK', 'PAM4', 'QAM16', 'QAM64', 'QPSK', 'WBFM']
    
  RML201610B:
    enabled: true
    epochs: 240
    batch_size: 128
    snr_levels: [-20, -18, -16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
    num_classes: 10
    class_names: ['8PSK', 'AM-DSB', 'BPSK', 'CPFSK', 'GFSK', 'PAM4', 'QAM16', 'QAM64', 'QPSK', 'WBFM']
    
  RML2018:
    enabled: true
    epochs: 120
    batch_size: 64
    snr_levels: [-20, -18, -16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
    num_classes: 24
    class_names: ['OOK', '4ASK', '8ASK', 'BPSK', 'QPSK', '8PSK', '16PSK', '32PSK', '16APSK', '32APSK', '64APSK', '128APSK', '16QAM', '32QAM', '64QAM', '128QAM', '256QAM', 'AM-SSB-WC', 'AM-SSB-SC', 'AM-DSB-WC', 'AM-DSB-SC', 'FM', 'GMSK', 'OQPSK']

# Training parameters
training:
  learning_rate: 0.01
  lr_decay_epochs: [120, 160, 200]
  lr_decay_rate: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  nce_k: 16384
  nce_t: 0.07
  nce_m: 0.9
  view_chose: "ALL"
  mod_l: "AN"
  n_1: 1.0
  n_t: 1.0
  feat_dim: 128
  num_workers: 8
  print_freq: 10
  save_freq: 120

# Automation settings
automation:
  sequential_execution: true
  cleanup_between_runs: true
  gpu_memory_threshold: 0.9
  max_retries: 3
  resume_on_failure: true
  save_intermediate_results: true
  generate_progress_plots: true
  
# Analysis settings
analysis:
  generate_tsne: true
  generate_comparison_plots: true
  statistical_analysis: true
  cross_dataset_evaluation: true
  convergence_analysis: true
  snr_sensitivity_analysis: true
  
# Reporting settings
reporting:
  generate_html_report: true
  generate_pdf_summary: true
  include_training_curves: true
  include_feature_visualizations: true
  include_statistical_tests: true
